bpDict = {
    ("anky", "ankylo", "ankylosaurus"): "Ankylo",
    ("arthro", "arthropluera"): "Arthro",
    ("argy", "argentavis"): "Argy",
    ("bary", "baryonix"): "Baryonix",
    ("basilo", "basilosaurus"): "Basilo",
    ("carno", "carnotaurus"): "Carno",
    ("carbo", "carb", "carbonemys", "turtle"): "Carbo",
    ("carchar", "carch", "carcharodontosaurus", "carcharo"): "Carchar",
    ("daedon"): "Daedon",
    ("doed", "doedicurus"): "Doed",
    ("diplo", "diplodocus"): "Diplo",
    ("giga", "giganto", "gigantosaurus"): "Giga",
    ("meg", "megalodon"): "Megalodon",
    ("roo", "procoptodon"): "Procoptodon",
    ("paracer", "racer", "paraceratherium"): "Paraceratherium",
    ("pela", "pelagornis"): "Pelagornis",
    ("pt", "pteranodon"): "Pteranodon",
    ("rex"): "Rex",
    ("bug", "rhynio", "rhyniognatha"): "Rhynio",
    ("quetz", "quetzal"): "Quetz",
    ("rhino"): "Rhino",
    ("stego", "stegosaurus"): "Stego",
    ("tape", "tapejera"): "Tape",
    ("mammut", "mammoth"): "Mammoth",
    ("spino"): "Spino",
    ("terror bird", "terror", "bird"): "Terror Bird",
    ("trike", "triceratops", "best line"): "Trike",
    ("tuso", "squid", "tusoteuthis"): "Tusoteuthis",
    ("theri", "therizinosaur"): "Theri",
    ("thyla", "thylacoleo"): "Thyla",
    ("mega", "megatherium"): "Megatherium",
    ("yuty", "yutyrannus"): "Yuty",
    ("comp", "bow", "compound bow"): "Compound Bow",
    ("longneck"): "Longneck",
    ("shotgun", "shotie"): "Shotgun",
    ("sword"): "sword",
    ("fabi", "sniper", "fabricated sniper", "sniper"): "Sniper",
    ("riot shield", "riot"): "Riot Shield",
    ("metal shield", "metal"): "Metal Shield"
}

tierDict = {
    ("ascendant", "asc"): "Ascendant",
    ("mastercraft", "mc"): "Mastercraft",
    ("journeyman", "jr"): "Journeyman",
    ("aprentice", "ap"): "Apprentice"
}
